all: success_test.cpp fail_test.cpp echo_test.cpp echo_extra_character_test echo_missing_newline_test
	g++ -o success_test success_test.cpp
	g++ -o fail_test fail_test.cpp
	g++ -o echo_test echo_test.cpp
	g++ -o echo_extra_character_test echo_extra_character_test.cpp
	g++ -o echo_missing_newline_test echo_missing_newline_test.cpp
	g++ -o multiline_output multiline_output.cpp
